name: ASP.NET Core CI using Docker

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macOS-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-16.04]
    steps:
    - uses: actions/checkout@v1
    - name: Build and test using Docker
      run: |
        chmod +x build.sh
        ./build.sh
      shell: bash
